# Generated by Django 4.0.2 on 2022-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Ali Amini', max_length=300)),
                ('phone_number', models.IntegerField(max_length=11, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
